[ai]
inline_tooltip = true
rules = ""
mode = "manual"

[ai.models]
custom_models = []
edit_model = "openai/gpt-5"
chat_model = "openai/gpt-5"
displayed_models = []

[ai.open_ai]

[ai.github]

[formatting]
line_length = 79

[language_servers.basedpyright]

[language_servers.pylsp]
enable_mypy = true
enabled = false
enable_pydocstyle = false
enable_flake8 = false
enable_pyflakes = false
enable_pylint = false
enable_ruff = true

[language_servers.ty]

[diagnostics]
sql_linter = true

[datasources]

[save]
format_on_save = false
autosave_delay = 1000
autosave = "after_delay"

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[display]
default_table_max_columns = 50
code_editor_font_size = 14
default_table_page_size = 10
default_width = "medium"
dataframes = "rich"
cell_output = "below"
reference_highlighting = false
theme = "light"

[completion]
copilot = "github"
activate_on_typing = true

[runtime]
default_auto_download = []
default_sql_output = "auto"
auto_instantiate = false
output_max_bytes = 8000000
auto_reload = "off"
on_cell_change = "autorun"
watcher_on_save = "lazy"
std_stream_max_bytes = 1000000
reactive_tests = true

[package_management]
manager = "uv"

[server]
browser = "default"
follow_symlink = false

[mcp]
presets = []

[mcp.mcpServers]

[snippets]
custom_paths = []
include_default_snippets = true

[experimental]
